login: &login
  adapter: mysql
  host: 127.0.0.1
  username: root
  password:
  socket: /private/tmp/mysql.sock

development:
  database: gitscm_development
  <<: *login

test:
  database: gitscm_test
  <<: *login

